### ISSUE TITLE
redundant version names

### ISSUE THREAD

**Issue by luyiming** [jenv/jenv#213]
There are lots of redundant versions after executing `jenv add <path-to-java-home>`. For example, my output of `jenv versions` is:
```
  1.7
  1.7.0.181
* 1.8 (set by /Users/luyiming/.jenv/version)
  1.8.0.162
  10.0
  10.0.1
  openjdk64-1.7.0.181
  oracle64-1.8.0.162
  oracle64-10.0.1
```
In fact I just installed 3 versions: java7, java8, java10. 

This seems cluttered. How do I remove those redundant versions?

**Comment by joostoudeman** [comment]
as far as I could find, you can remove the links from ~/.jenv/versions.

**Comment by andrewflbarnes** [comment]
To remove a version run `jenv remove <alias>`.

The multiple aliases are by design and allow jenv to support several use cases including
- needing less specific versions
- needing more specific versions
- having multiple versions installed with the same major/minor
- having the sdame version by different providers (e.g. corretto vs openjdk)
