### ISSUE TITLE
jenv add does not work on macos catalina when java installed with brew cask

### ISSUE THREAD

**Issue by wnck** [jenv/jenv#272]
### macos catalina

I installed the newest version of java with `brew cask upgrade`.  After this I tried to add the resulting JDK to jenv with `jenv add /Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home`. Then I got the following message in a separate window:

openjdk-13.0.1.jdk cannot be opened because the developer cannot be verified.

Seems to be a new security policy in catalina. How do I get around this?

**Comment by dukechem** [comment]
Similar issue, apparently with macos (not jenv), and extensive discussions of many work-arounds:
[https://github.com/hashicorp/terraform/issues/23033](https://github.com/hashicorp/terraform/issues/23033)

**Comment by devdyce** [comment]
Didn't see it mentioned in the above thread but you're also able to navigate to Security Privacy Settings and enable the specific binary from System Preferences after you let `jenv add /Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home` fail. 

System Preferences --> Security & Privacy --> General (towards the bottom you'll be able to enable openjdk-13.0.1.jdk

**Comment by wnck** [comment]
After enabling openjdk-13.0.1.jdk in the System Preferences I added it again to `jenv` then it worked. Afterwards I removed (`jenv remove ...`) the corrupt entry which was added when the catalina security interrupted my action.

Thanks to @dukechem and @devdyce !

**Comment by coryfklein** [comment]
In Ventura trying to install Trava-jdk-11-dcevm I had a hard time with the System Preferences workaround because the JDK is published as a folder and macOS doesn't recognize it as an application, so clicking "Open Anyway" would just open the directory in Finder and my next `jenv add` would still fail.

I worked around this by tricking macOS into thinking it was an application by adding the `.app` extension:
```
mv dcevm-11.0.15+1 dcevm-11.0.15+1.app
```
Then I double-clicked it in finder – which failed the security check – then went to System Preferences again and clicked "Open Anyway" and **then** went back and re-ran `jenv add` and it finally worked.
