### ISSUE TITLE
Multi Versions added for only one JDK folder

### ISSUE THREAD

**Issue by lty2008one** [jenv/jenv#370]
I'v installed zulu-jdk-8 and zulu-jdk-17 for my m1pro Mac.
But when I entered `jenv add /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home`
there are 3 versions added like
```shell
1.8
1.8.0.332
zulu64-1.8.0.332
```
They seem to be linked to the same folder

**Comment by lty2008one** [comment]
How can I manage my versions or rename them?

**Comment by lty2008one** [comment]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/52694802/178892994-6499e65e-f931-4081-bd0a-a2b37a073b84.png">

**Comment by lty2008one** [comment]
Can I simply delete link files or rename them to manage versions ?

**Comment by marquiswang** [comment]
You can. You can also use `jenv remove` and `jenv add` to manually add aliases.

**Comment by tjnycum** [comment]
I'm pretty sure this behavior is intentional, because it's useful in a few ways. One way: If in your .java_version files you specify the versions with no more specificity than you need (e.g. 1), then you don't have to update them whenever you install a different version that still meets the needs of those projects (e.g. a newly released 1.1). If you specify the full version string (e.g. 1.0.0.0), then you have to update the .java_version any time any part of it changes. On the other hand, if you remove all but the "1" link, then you can't specify a more specific version in another project. So it creates a link for each level of specificity the user might need.

**Comment by davewichers** [comment]
@marquiswang - How do you 'manually add aliases'? jenv add take a path to the proper Contents/Home dir of a JDK, but I have no clue how to add a custom alias that's not autogenerated when running jenv add this way.

**Comment by andrewflbarnes** [comment]
@davewichers - you can do this with the "long" form of jenv add:
```bash
jenv add alias /path/to/java/home
```

You will get a warning about deprecation but I don't think this feature is going anywhere soon and if anything I expece the deprecation warning will be removed at some point. e.g.
```
$ jenv add my-alias ~/.sdkman/candidates/java/21.0.2-amzn/
Warning : jenv add alias path/to/java_home is deprecated.
Please prefer to let jenv generate unique alias name by using

    $ jenv add path/to/java_home

my-alias added
```
