### ISSUE TITLE
Oracle Java 1.8

### ISSUE THREAD

**Issue by hidvegin** [jenv/jenv#389]
I would like to add Oracle Java 1.8.361.09 to `jenv`.

```
/usr/libexec/java_home -V
Matching Java Virtual Machines (4):
    19.0.2 (arm64) "Oracle Corporation" - "Java SE 19.0.2" /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
    17.0.6 (arm64) "Eclipse Adoptium" - "OpenJDK 17.0.6" /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    1.8.361.09 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
    1.8.0_292 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 8" /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
```

But when I use `jenv add /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` code, I got this error:

```
Warning : jenv add alias path/to/java_home is deprecated.
Please prefer to let jenv generate unique alias name by using

    $ jenv add path/to/java_home

/opt/homebrew/Cellar/jenv/0.5.6/libexec/libexec/jenv-add: line 56: cd: Plug-Ins/JavaAppletPlugin.plugin/Contents/Home: No such file or directory
```

How could I resolve this error?

**Comment by andrewflbarnes** [comment]
Looks like your problem is the path has a space in it and you aren't escaping or wrapping it with quotes.

Try running
```bash
jenv add "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
```

Without quotes/escaping, jenv is treating that location as two separate strings with the first being an alias (`/Library/Internet`) and the second being the location (`Plug-Ins/JavaAppletPlugin.plugin/Contents/Home`).

The cd error is a result of the second string not being a valid location.

**Comment by hidvegin** [comment]
Thank you for your answer. This was the problem.
