### ISSUE TITLE
Conflict with Android studio?

### ISSUE THREAD

**Issue by mvevitsis** [jenv/jenv#407]
With jenv installed on Mac OS, I get the following error every time I open my terminal:

(eval):export:1: not valid in this context: Fusion.app/Contents/Public:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/Matvei/Library/Android/sdk/tools:/Users/Matvei/Library/Android/sdk/build-tools/28.0.2:/Users/Matvei/bin

**Comment by jeffreyjackson** [comment]
any update on this one?

**Comment by sharpred** [comment]
I have had jenv working perfectly for some months until today when, after upgrading MACOS, I started getting this same error reported by @mvevitsis. The thing we have in common is VMWare Fusion, which I also installed yesterday.  I completely removed VMWare fusion (it's a PITA to remove) and the problem went away.

If you can't / don't want to remove VMWare Fusion, you can try uncommenting the line

`eval export PATH="/Users/XXX/.jenv/shims:${PATH}"`

From your bash/zsh profile. This *appears* to work ok without too many side effects (not tested exhaustively, YMMV and all that)

**Comment by jeffreyjackson** [comment]
interesting, I also have fusion installed 👍🏻  thanks for the heads up

**Comment by andrewflbarnes** [comment]
This looks like a problem of a PATH path having a space in it and eval being used on the export instead of just exporting.

As an example
```bash
# this works
export BLAH="/path/1:/path/2:/path 3/with a/space and/more"
# this doesn't
eval export BLAH="/path/1:/path/2:/path 3/with a/space and/more"
```

In your bash/zsh profile, just change the `eval export PATH...` to `export PATH...` and it should work - this aligns with both the repo and site documentation.

I don't see anything in the current documentation or git history which says to use `eval export ...` so I don't think there's any documentation which needs correcting so will close.

If you find the issue persists even after removing `eval` please feel free to re-open.

**Comment by jeffreyjackson** [comment]
fwiw, I recently got a new Mac and reinstalled everything - including fusion, jenv, etc.  and the installation went smooth and ive not seen this issue again.
